### ISSUE TITLE
2D plotting color assignment

### ISSUE THREAD

**Issue by cfandel** [cgre-aachen/gempy#101]
Several questions related to plotting:
1. In gempy's 2D plotting (`gempy.plotting.plot_section()`) I'm missing a formation from the key. (See [this](https://github.com/cfandel/gempy/blob/master/notebooks/prototype_notebooks/Chloe_Gottesacker/Gottesacker_geology_v7.ipynb) notebook, section 10 - Schrattenkalk, the green unit, is missing, even though it's present on the map and when I print `get_series()`). Any ideas why & how to fix?
2. I'd like to be able to adjust the colormap for plotting - how/where is it assigned?
3. I'd also like to use the gempy colormap to plot imported rasters. Is it possible to return something like a dictionary of which integers in the lith block array are mapped to which formations?
4. GemPy is creating a model that matches the general _pattern_ of the actual geology, but the unit assignments seem to be really off. Is there a way to tell if this is a plotting error or whether something else is going on? See the last section of the linked notebook.

I'm doing some of these things I think inefficiently already in the linked notebook, but it seems like there might be a better way using GemPy's already-built capabilities?
Thanks!

**Comment by Leguark** [comment]
1. Mmm it seems that there is no point of the Scrattenkalk in the plot. Can be that the interface point is outside the extent?

2. Mmm it is more convoluted that it should. It is assigned in gempy.plotting.visualization.PlotData2D . The colormap is created in the colors.py file. @pytzcarraldo  may be able to help you more.

3. you can import the color map from colors.py

4. By looking the input data in cell In[10] I would say that the problem is lack of data for the more detailed structures but is not easy to tell. It is an interesting case to use off-contact constrains in a probabilistic approach

**Comment by cfandel** [comment]
Thanks!
I think I can fix/figure out 1,2,3, but for the last question, what do you mean by off-contact constraints?
I'm treating the land surface as a contact in some areas, but the rest of the data points are at boundaries between two units. Is it possible to use data points that aren't at a boundary?

**Comment by Leguark** [comment]
I did not realise, I didnt answer this question! Off-surface constrain only can be used as inverse information in a bayesian (or optimisation) approach
