### ISSUE TITLE
Error with numPy 1.16.0 

### ISSUE THREAD

**Issue by JfosterBGC** [cgre-aachen/gempy#106]
It seems that the new version of numpy (1.16.0 release 20190113) returns the following error: 

AttributeError: module 'numpy.core.multiarray' has no attribute '_get_ndarray_c_version'

when trying to run gempy.InterpolatorData

**Comment by Leguark** [comment]
That looks ugly. It seems some incompatibility between theano and numpy. I am going to test if in Linux I have the problem

**Comment by Leguark** [comment]
Yes you are very right. I got the same error. Just downgrade the numpy version using:
`pip install numpy==1.15.4`

Thank you for catching the bug!

**Comment by ejhgeo** [comment]
I've had a similar issue. The above fix didn't work for me. I was trying to run the unit tests to make sure everything installed correctly, but the test can't even run because of a numpy problem with 'numpy.core._multiarray_umath'. I have tried running pytest with the numpy automatically installed with 'pip install gempy' and reinstalling numpy with pip, and get the following error:

ImportError while loading conftest '/anaconda3/envs/testenv/lib/python3.5/site-packages/test/conftest.py'.
test/conftest.py:3: in <module>
    import gempy
gempy/__init__.py:16: in <module>
    from .gempy_front import *
gempy/gempy_front.py:33: in <module>
    import numpy as _np
numpy/__init__.py:142: in <module>
    from . import core
numpy/core/__init__.py:47: in <module>
    raise ImportError(msg)
E   ImportError:
E
E   IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
E
E   Importing the multiarray numpy extension module failed.  Most
E   likely you are trying to import a failed build of numpy.
E   Here is how to proceed:
E   - If you're working with a numpy git repository, try `git clean -xdf`
E     (removes all files not under version control) and rebuild numpy.
E   - If you are simply trying to use the numpy version that you have installed:
E     your installation is broken - please reinstall numpy.
E   - If you have already reinstalled and that did not fix the problem, then:
E     1. Check that you are using the Python you expect (you're using /anaconda3/bin/python),
E        and that you have no directories in your PATH or PYTHONPATH that can
E        interfere with the Python and numpy versions you're trying to use.
E     2. If (1) looks fine, you can open a new issue at
E        https://github.com/numpy/numpy/issues.  Please include details on:
E        - how you installed Python
E        - how you installed numpy
E        - your operating system
E        - whether or not you have multiple versions of Python installed
E        - if you built from source, your compiler versions and ideally a build log
E
E        Note: this error has many possible causes, so please don't comment on
E        an existing issue about this - open a new one instead.
E
E   Original error was: No module named 'numpy.core._multiarray_umath'

I've tried some of the suggested steps, and have tried different versions of numpy as suggested in this issue, but get the same error. I have also tried installing gempy with conda to see if that made a difference and get the following error: 

ImportError while loading conftest '/anaconda3/envs/testenv/lib/python3.5/site-packages/test/conftest.py'.
test/conftest.py:3: in <module>
    import gempy
gempy/__init__.py:16: in <module>
    from .gempy_front import *
gempy/gempy_front.py:33: in <module>
    import numpy as _np
numpy/__init__.py:142: in <module>
    from . import add_newdocs
numpy/add_newdocs.py:13: in <module>
    from numpy.lib import add_newdoc
numpy/lib/__init__.py:8: in <module>
    from .type_check import *
numpy/lib/type_check.py:11: in <module>
    import numpy.core.numeric as _nx
numpy/core/__init__.py:26: in <module>
    raise ImportError(msg)
E   ImportError:
E   Importing the multiarray numpy extension module failed.  Most
E   likely you are trying to import a failed build of numpy.
E   If you're working with a numpy git repo, try `git clean -xdf` (removes all
E   files not under version control).  Otherwise reinstall numpy.
E
E   Original error was: cannot import name 'multiarray'

I'd assume this will cause problems with using gempy down the line (which I haven't been able to do yet because of install problems). Any suggestions on how to fix this? I'm very new to programming and python, so details are helpful. Thanks.

**Comment by Leguark** [comment]
uff, I am not sure where is coming that from. Can you work with numpy indepently of gempy? Because it seems a problem of linking numpy and its compilers and nothing to do with gempy

**Comment by ejhgeo** [comment]
I've used numpy before and have never had this problem. Seems only to happen when trying to import 'multiarray'. I can go ahead and just forego doing pytest for now, but if gempy requires 'core._multiarray_umath' at anypoint then I may have a problem. I assume the numpy automatically installed by 'pip install gempy' is the one that should work?
