### ISSUE TITLE
Pandas error when running GemPy paper-gravity examples

### ISSUE THREAD

**Issue by lperozzi** [cgre-aachen/gempy#139]
Hi all,

many thanks for developing `GemPy`. 
I've installed it in a conda env and I also installed `vtk`,`steno3D`, `pymc and pymc3`, and related package without problems. However, when I run this command:

```geo_data_g.add_interface(X=10, Y=4, Z=-7, formation='fault1')```

I have the following error:

```ValueError: Cannot setitem on a Categorical with a new category, set the categories first```

I tried to downgrade `pandas` without success. Did someone had the same problem?

This is my machine:

```
compiler   : GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)
system     : Darwin
release    : 18.5.0
machine    : x86_64
processor  : i386
CPU cores  : 12
interpreter: 64bit
```

Many thanks for your help

**Comment by Leguark** [comment]
Hi there,
glad to know we got a new user!

I guess that the problem is that 'fault1' does not  exist in the formation dataframe (geo_data_g.formation). You will need to define first the formation and then it should allow you. You can also brute forced it by adding the category to geo_data.interfaces['formation'].cat.add_category (look  up exactly the pandas method, I just wrote it from memory).

Sorry for the inconvenience. We are working a lot to make all the data management much more robust in the next version.
