### ISSUE TITLE
What are the units on forward gravity results and boundary conditions?

### ISSUE THREAD

**Issue by ejhgeo** [cgre-aachen/gempy#142]
In running the forward gravity, what are the units on the resulting gravity map? There is a colorbar but no label. I would assume mGal, as is standard and as in the paper, but the values I'm getting are off. I have run a test using a simple buried cylinder of thickness 6 km and radius 10 km, buried right below the surface, with a density anomaly of 400 kg/m^3. This shape has a closed form solution and results in a gravity signal of about 72.72 mGal at the surface over the center of the cylinder. I get a similar number using a 2D forward gravity model I wrote in Matlab, but when I put this simple cylinder into GemPy and run the gravity, I get a value of 4.95 (but 4.95 what?) over the center of the cylinder. 

The true value and Gempy's value are clearly very different, so is it a unit difference? or is there a deeper problem in the calculation of the gravity? Without units, it's difficult to understand the results GemPy is giving.

Also, how do the boundaries (i.e. the padding on the model extent required by gempy) affect the gravity calculations and what is the error associated with increasing that padding? And, how does GemPy calculate the differential density from the absolute densities we define for the various formations? 

Thanks.

**Comment by Leguark** [comment]
First of all the geophysical module is highly experimental in general. We are working with the guys of pygimli to make both libraries compatible and hence a decent way to compute geophysics.

Now, the way gravity is implemented in gempy is really basic, we just compute the sum of the component z of the absolute pull (density times volume). It is the same implementation (in principle) as in noddy and the relative fields are analogous. 

You are right that the absolute results are difficult to interpret, it would be great if a geophysicist could give a bit of feedback in this one. Usually when I want to do inversion I just normalize both fields (by shifting and scaling).

Regarding the padding, since we are just looking at the z component, as we move farther this component gets really small. Right now I select the voxels within half sphere around the device  so as long the padding is big enough that you don't "run out of voxels".

In any case, GemPy would need an owner for the geophysics so I would be happy if you can contribute in this side!

Cheers
