### ISSUE TITLE
get formation number

### ISSUE THREAD

**Issue by lllxllll** [cgre-aachen/gempy#161]
![image](https://user-images.githubusercontent.com/45480246/56646670-931eec80-66b2-11e9-960b-7b7eb2e74b03.png)
why I can not get the formation number?

**Comment by Leguark** [comment]
when you use gp. you are invoking gempy functionality. get_formation_number is a method of geo_data. By the way the screenshot is very misleading because you are no showing all the code.

Please just follow the bug report template (just set) or this guidelines (https://github.com/codeforamerica/howto/blob/master/Good-GitHub-Issues.md) for a better way to create issues.
