### ISSUE TITLE
Tutorial of uncertainty analysis 

### ISSUE THREAD

**Issue by gislijun** [cgre-aachen/gempy#209]
Is there any code about uncertainty analysis in Gempy 2.0? If can I need a tutorial about it.

**Comment by Leguark** [comment]
It is where I am working right now. In the a general sense, all you need is a sampler (pymc) and geo_model.modify_surface_point or ...orientation and the recompute the model. 

If you let me know (if you want privately) what your project is about, I can try to help and share some working in progress files. Otherwise you will need to wait a couple of months until the bayesian engine is up and published.

**Comment by gislijun** [comment]
Thank you so much for your answer. My study project is to assess the uncertainty of my model. I just try to use the existing interface in gempy. I am a newbie at python. Just thank you.
