### ISSUE TITLE
plot_section_by_name

### ISSUE THREAD

**Issue by bistek** [cgre-aachen/gempy#217]
Hello, I'm running the tutorial notebook ch1-3b-Sections, downloaded on September 23, and at one of the last steps I get this error:

`gp.plot.plot_section_by_name(geo_model, 'section1')`

yields:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-19-7a807160f3d2> in <module>
----> 1 gp.plot.plot_section_by_name(geo_model, 'section1')

AttributeError: module 'gempy.plot.plot' has no attribute 'plot_section_by_name'
```

Thanks!

**Comment by elimh** [comment]
Hi bistek!
I guess you installed gempy via pip, right? Because unfortunately, the function plot_section_by_name is something that is not yet part of the latest pip release, as it was added within the last two weeks.  We will be releasing a new pip version shortly so that all notebooks in the master branch will work with it. Otherwise, if you want to use this feature now, I recommend cloning gempy directly from github, so you always have the latest version of notebooks and code. 
Thanks a lot for pointing that out!
Elisa

**Comment by bistek** [comment]
Dear Elisa, thanks very much!

As I understand you suggest to keep updating with git the main branch on my PC? I understand that his can be easily done since it is just Python so there is nothing to compile etc.

Good!

**Comment by elimh** [comment]
Exactly :)

**Comment by bistek** [comment]
Hello, I am afraid that it is not possible to plot the potential field in a cross section, since the options are:

`function gempy.plot.plot.plot_section_by_name(model, section_name, show_faults=True, show_topo=True, show_data=True, show_all_data=False)`

Do you have some suggestion?

Thanks!!

**Comment by elimh** [comment]
Oh hi, sorry for the late reply! There is the function `gp.plot.plot_section_scalarfield(geo_model,section_name='section1', sn=0)`. Sn is the scalar field number, the order is like in geo_model.series (0 is therefore the youngest fault, if you have one)

**Comment by bistek** [comment]
Thanks very much!
