### ISSUE TITLE
kirging parameters reset after compute_model, set_interpolation_data

### ISSUE THREAD

**Issue by AndrewAnnex** [cgre-aachen/gempy#232]
**Describe the bug**
I am running into an issue where the kriging parameters are overwritten to the defaults after running `set_interpolation_data` or `compute_model`

generally there is also little documentation about the parameters as well and how changing them modifies output models

**To Reproduce**
specifically, init a model with data, then attempt to run `set_interpolationd_data` any kriging data fields are now reset,
if kriging parameters are updated after setting the interpolator, most parameters stick, however after running `compute_model` any drift equations set are reset to defaults (I am attempting to override [3, 0] with [0, 0])

**Expected behavior**
once modified, kriging parameters should stay that way

**Comment by Leguark** [comment]
Yes, I was half aware of this. 
I have it like this because it is difficult to control that if the user change the model all the kriging parameters update accordingly. Thank you for the extra analysis. 

I guess that in set_interpolator I will add an argument to decide if setting them or not and in compute_model I will remove the call to set default values.

I hope to find some time at beginning of the year to sprint on all this minor bugs (or find someone who is willing to).

**Comment by Leguark** [comment]
Solved in 294015013066870f4808f7062ad18362cf50b258
