### ISSUE TITLE
How to deal best? Surface does not exist in borehole

### ISSUE THREAD

**Issue by domist07** [cgre-aachen/gempy#350]
If I have these three boreholes as input data:
![SurfaceCutOutPre](https://user-images.githubusercontent.com/59735059/78237199-460ae380-74db-11ea-8d68-ac8fdbbfe48b.png)
The three surfaces are in a separate series and have an erosion relation. If I only get as input the contact points of the surfaces from my boreholes, GemPy will model the red dotted line, but I think the red continuously line is more realistic. Otherwise the red surface exist in the middle borehole which is false.
![SurfaceCutOut](https://user-images.githubusercontent.com/59735059/78237211-4c00c480-74db-11ea-9687-4852374ef8d1.png)
A fix for the problem is, to set a "help point" (light red) for the red surface above the yellow surface in the middle borehole. Making this automatically I want to write a peace of code. Do you think it is better to define a "hard" value like 1m, to set the red help point over the yellow point or do you think a relativ value like 5% of surface thickness, is better?

**Comment by javoha** [comment]
Hi domist7,

from my perspective there is no correct answer to this. First of all it really depends on how much you trust your data and your expertise. How confident do you feel about the model you aim to realize (continuos red line). Is this "pinching out and back in" realistic? Do you trust your data or is there a possibility that the point is just missing in the central borehole? 

Apart from that, if you are sure you want it to beahve this way, I like your solution. However the decision of how "far up" you put the red surface point in the central borehole should then also be driven by other knowledge, because from a data-driven/implicit/gempy view there is no argument to put it in a certain position.

Do you agree and do you maybe have other information available to make a decision? Or what are your thoughts on this?

Best wishes and stay healthy!

**Comment by Leguark** [comment]
Hi Dominik,

yes, you go in the right direction. In principle if a layer disappear it is fair to assume that it was an erosion. I think adding the "help point" is a great idea and 5% may be a good default value **but** what we need - on the long term - is a class that deals with borehole data.

My idea is to have a class where we load the raw data and then has export methods to the SurfacePoints considering different scenarios and one of them would be these missing contacts.

Here I have something very similar to what you propose https://github.com/cgre-aachen/gempy/blob/master/notebooks/integrations/GemPy-Striplog.ipynb

**Comment by domist07** [comment]
Ok, thanks for your advices!
