### ISSUE TITLE
“LinAlgError”

### ISSUE THREAD

**Issue by wh19971014** [cgre-aachen/gempy#388]
When the code run the step:"gp.compute_model(geo_model)" , it occured “LinAlgError”,i don't know what it means.
![png](https://user-images.githubusercontent.com/60054308/79955719-c35dbe80-84b1-11ea-942b-3307cfa1254a.png)

**Comment by AlexanderJuestel** [comment]
Hello, 

for my models, I can solve the problem by adding orientations for certain lithologies in the fault blocks where I do not have orientations for this particular lithology. 

Especially when models get bigger, I can recommend, based on own experience, that it is practical to load surface by surface into the model and compute the model instead of loading all surfaces at once. It may take more time but it is worth effort as you can easily determine which lithology or fault is causing problems and easily fix the issue then. 

Hope that helps

PS: In case you do not have measured orientations in a fault block, maybe assume like an average value for now.
