### ISSUE TITLE
Clean up dependency version handling

### ISSUE THREAD

**Issue by alexanderzimmerman** [cgre-aachen/gempy#505]
I'm not sure when we'll get around to addressing this, but the way we manage dependencies is starting to look a little too messy to me.

Here is what `requirements.txt` looks like right now on master:

```
pandas
Theano>=1.0.4 # In windows use conda! This will install all the required compilers
matplotlib
numpy
pytest
seaborn>=0.9
networkx
scikit-image>=0.17
pyvista # 0.24 and 0.25 compatible
pyvistaqt # necessary for > 0.25
iPython
```

and `optional_requirements.txt`:

```
# Interactive pandas
qgrid==1.3.0
# Probability
pymc3
arviz
# vtk plugins
pyvistaqt
pyevtk

# AR
pyqrcode

# Plot orientation
mplstereonet
welly
# gdal # install gdal with conda! `conda install gdal`
```

along with the optional requirements, many of the examples have other dependencies which are only documented in `.travis.yml`, e.g.

```
  - conda install -c conda-forge python-graphviz emg3d==0.11
    discretize==0.4.13 pip matplotlib ipython six pytest pytest-cov
    pytest-mock gdal pandas seaborn>=0.9 qgrid sphinx-gallery
    ipywidgets pyevtk arviz dataclasses scikit-image>=0.17
    recommonmark networkx panel setuptools mkl-service
```
```
  - conda install -c anaconda libffi
```
```
  - pip install welly pymc3
```

Also a careful reading of the `.travis.yml` reveals more restrictive version requirements, e.g.
```
  - pip install pyvista==0.24.3 --force-reinstall
```

**Comment by alexanderzimmerman** [comment]
@Leguark and @alex-schaaf , am I missing anything in the overview of this problem? 

Do we think we'll always have `.travis.yml` specifying versions or is there a way to handle that entirely in `setup.py` and/or `requirements.txt`?

**Comment by prisae** [comment]
- I would avoid having stuff in `setup.py` and `requirements.txt`, in order to have as little duplication as possible. One way many projects use is to specify all hard dependencies in `setup.py`, and then have a `requirements.txt` that only contains
   ```
  .
  ```
   or
   ```
  -e .
  ```
  . This will make that any workflow that uses `requirements.txt` checks `setup.py` for installation.
- Everything that is a soft dependency would then go into `optional_requirements.txt` - but there could be different ones for different purposes, as you might not want everything installed at ones. E.g., `requirements_docs.txt` that contains everything to build the docs, `requirements_this.txt` that contains everything for purpose `this`, etc.

**Comment by prisae** [comment]
For reference: https://stackoverflow.com/a/49684835

**Comment by alexanderzimmerman** [comment]
I'm consolidating this into #506 .
