### ISSUE TITLE
Using gempy with pyvista - export to vtk

### ISSUE THREAD

**Issue by shakasaki** [cgre-aachen/gempy#531]
**What is your question?**
I'm trying to include some graphics generated from pyvista and to show this in a 3D plot along with a gempy geo-model. Also, i'd like to eventually be able to export the gempy model (surfaces and orientations) to a vtk graphics file. 
Is this possible? I looked around and couldn't find how to do this. I'm using gempy 2.2.3
Thank for the help and developing this awesome tool - !

**Comment by AndrewAnnex** [comment]
as soon as you have a pyvista object you can export to VTK using the .save function. It is pretty easy to make a point cloud using the polydata class in pyvista from the pandas dataframes used for gempy. There are built in functions in the tutorials for gempy to export surfaces to vtk objects, although I think that it requires additional dependencies like pyevtk.

**Comment by shakasaki** [comment]
Hi Andrew and thanks for the response. I am creating a model of fault surfaces in gempy using points and orientations. The final model I am interested in is simply a collection of surfaces. I would like to display that in (e.g.,) paraview, so to export as VTK. 
I was not able to run the .save function you mentioned to save this model in VTK format.
I create the model using 
`geo_model` = `gp.create_model('my_model')`

and then, after obtaining the surfaces, I plot using
`gp.get_data(geo_model, 'surfaces')`

This opens an interactive pyvista window, but I do not see what you mean by pyvista object. 

Apologies for the very basic question!

**Comment by AndrewAnnex** [comment]
@alex-schaaf I suggest reading the tutorials first if you haven't already https://docs.gempy.org/tutorials/ch1_fundamentals/ch1_7_3d_visualization.html#sphx-glr-tutorials-ch1-fundamentals-ch1-7-3d-visualization-py. 

GemPy uses the pyvista API within the source code (https://github.com/cgre-aachen/gempy/blob/master/gempy/plot/vista.py) to create pyvista objects that are plotted with pyvista. By reading that class, you can find where these objects are made. The .save function I mentioned was for the pyvista objects not for GemPy. 

However, since you just want to export the objects  the easier option is the "export_to_vtk" function https://github.com/cgre-aachen/gempy/blob/master/gempy/plot/visualization_3d.py#L1196 or confusingly also in https://github.com/cgre-aachen/gempy/blob/master/gempy/plot/_plot.py#L79. One or both of those should work to save your surfaces out as vtk files. 

To save out the input data points/orientations as vtk files it is pretty trivial to convert your input dataframes into pyvista objects for export. I don't think Gempy has a function to export the points/orientation data, so I think you would need to look at the class I linked at the top here for examples for how to use the pyvista API.

**Comment by Leguark** [comment]
It is true, for the input we do not have an official way to export it. I imagine that using the pyvista interface it should be relatively easy. `export_to_vtk` really needs a rework and just be a function of the `plot` module using pyvista functionality

**Comment by shakasaki** [comment]
would be a nice functionality to have at some point! Thanks for the input
