### ISSUE TITLE
Vertices_of_Cutting_Faults

### ISSUE THREAD

**Issue by Ali1990dashti** [cgre-aachen/gempy#546]
Dear Community,
hope doing well and being healthy.
**What is your question?**
Is it possible in Gempy to see the relationship between faults in their vertices? I have already gone through [this notebook](https://github.com/Japhiolite/gempy-tests/blob/master/notebooks/Test_models.ipynb), but it seems that it is working only for 2d. I want to cut one of my faults when it meets the two other ones and also I want to cover one fault with the upper lithology. In my model I used `geo_model.set_fault_relation()` to do it but for me it was not successful. I am using `2.2.7` version of Gempy. The point is that I want to see it in the vertices. In the following I copied my syntax and also a picture showing the vertices I am looking for:

![Simple](https://user-images.githubusercontent.com/62764899/99383847-c6e1e880-28ce-11eb-98fa-de66d9ab3523.jpg)

```
import gempy as gp
import numpy as np
import pandas as pd
geo_model=gp.create_model('generic')
geo_model = gp.init_data(geo_model, extent=[0,120,0,80,0,100], resolution=[50,50,50])
geo_model.set_default_surfaces()
geo_model.add_surface_points(X=5, Y=40, Z=60, surface='surface1')
geo_model.add_surface_points(X=50, Y=40, Z=80, surface='surface1')
geo_model.add_surface_points(X=95, Y=40, Z=60, surface='surface1')
geo_model.add_orientations(X=27.5, Y=40, Z=50, surface='surface1', orientation=np.array([270,21.80140949,1]))
geo_model.add_orientations(X=72.5, Y=40, Z=50, surface='surface1', orientation=np.array([90,21.80140949,1]))
geo_model.add_features('Fault_w')
geo_model.add_surfaces('fault_w')
geo_model.add_features('Fault_E')
geo_model.add_surfaces('fault_E')
geo_model.add_features('Fault_2')
geo_model.add_surfaces('fault_2')
geo_model.add_surface_points(X=15, Y=40, Z=80, surface='fault_w')
geo_model.add_surface_points(X=25, Y=40, Z=40, surface='fault_w')
geo_model.add_orientations(X=40, Y=40, Z=60, surface='fault_w', orientation=np.array([90,90,1]))
geo_model.add_surface_points(X=95, Y=40, Z=90, surface='fault_E')
geo_model.add_surface_points(X=85, Y=40, Z=60, surface='fault_E')
geo_model.add_orientations(X=90, Y=40, Z=70, surface='fault_E', orientation=np.array([260,71.56505118,1]))
geo_model.add_surface_points(X=50, Y=40, Z=35, surface='fault_2')
geo_model.add_surface_points(X=40, Y=40, Z=30, surface='fault_2')
geo_model.add_orientations(X=45, Y=40, Z=32.5, surface='fault_2', orientation=np.array([270,26.56505118,1]))
gp.map_stack_to_surfaces(geo_model, {'Layers':('surface1','surface2'),
                                     'Fault_2':'fault_2', 'Fault_w':'fault_w', 'Fault_E':'fault_E'})
geo_model.set_is_fault(['Fault_w', 'Fault_E', 'Fault_2'])
fr = np.array([[False, False, True, False],
              [False, False, False, False],
              [False, False, False, False],
              [False, False, False, False]])
geo_model.set_fault_relation(fr)
gp.set_interpolator(geo_model, output=['geology'], theano_optimizer='fast_compile')
sol=gp.compute_model(geo_model)
gp.plot_3d(geo_model, plotter_type='background')
```

In advance, I do appreciate any help.

**Comment by javoha** [comment]
Hello @Ali1990dashti ,

as far as I can tell you set your order relations correctly. The problem is that you are missing input data in some fault blocks. In this case this means you need some input data for the fault you want to be offset in the left and right fault block. In your example you only have two surface points as input in the center. 

As an example: I added a single point two the `fault_2`:
`geo_model.add_surface_points(X=5, Y=40, Z=50, surface='fault_2')`

The result looks like this:
![image](https://user-images.githubusercontent.com/38279459/99562100-fe808b80-29c7-11eb-8532-509fb2a75319.png)

I hope this helps. One problem is that the offset needs to be based on some input data for the fault series in question. The offset can not be based on the sedimentary series, as two different scalar fields are calculated.

Best wishes and good luck
Jan

**Comment by Ali1990dashti** [comment]
Dear @javoha ,

thanks a lot for your comment and help. I will follow your suggestion to modify the model.

Take care and stay healthy,
Ali
