### ISSUE TITLE
surface points : Invert bottom to top of the formation

### ISSUE THREAD

**Issue by Magniel** [cgre-aachen/gempy#551]
Hi there! I'm very new in GEMPY and am currently working on the tutorial 1.1 -Basics of geological modeling with GemPy
I'd like to manage surface_points with Z linked with the  **top of a formation rather than the bottom** as I manage a regional model with a lot of shallow borehole not reaching the bottom of the main formations.
On the tutorial I can read : "_If such points are needed to resemble a top of a formation (e.g. when modeling an intrusion), this can be achieved by defining a respectively inverted orientation measurement._"
That's sound great, but I can't figure out how to define a "respectively inverted orientation measurement". 
Could you please help me?

**Comment by javoha** [comment]
Hello @Magniel,

actually I have never tried this myself. The idea would be to use orientations that point downwards instead of upwards. Say a standard orientation pole vector of a horizontal layer would be (0,0,1) pointing upwards. You could try using (0,0,-1) pointing downwards. You might also need to readjust the order of your formations. 
Again, I have not tried that and what is possible also depends on your exact data configuration. If you are able to share it we might be able to provide more help.

Good luck and best wishes
Jan

**Comment by Magniel** [comment]
Thanks for the tip Jan! By now, I haven't got the time to test your solution, but it sounds a good option. I'll keep you in touch. Best wishes! Mat.

**Comment by AlexanderJuestel** [comment]
Hey @Magniel, 

any update on that?

**Comment by Magniel** [comment]
Not really. Finally I decided to work classically with bottom rather than top. It's not an issue to me anymore.
