### ISSUE TITLE
Adding new export format: PFLOTRAN r(eactive transport code) and FLAC3D (geomechanics)

### ISSUE THREAD

**Issue by MoiseRousseau** [cgre-aachen/gempy#557]
Hi all,

I would like to contribute and to add two export formats to those already available. The first is for exporting to the subsurface reactive transport code PFLOTRAN (www.pflotran.org) and the second is for FLAC3D a geotechnical software (https://www.itascacg.com/software/flac3d).

Regards,
Moise

**Comment by AlexanderJuestel** [comment]
Hey @MoiseRousseau,

That sounds like a good idea but sorry for the very late reply! Have you heard about the GemGIS package that we are also maintaining (https://github.com/cgre-aachen/gemgis)? In order to keep the geological modeling within GemPy, we could implement your export feature in GemGIS, which was initiated for the processing of spatial data for geomodeling and exporting GemPy data to other formats would perfectly fit in there!

Looking forward to your response!
Alex

**Comment by MoiseRousseau** [comment]
Hi @AlexanderJuestel ,
Sorry for the late reply also. Note at the time of the creation of the issue, the export scripts were already written for GemPy. These scripts were written taking the MOOSE export capability of GemPy as a template. 
Concerning GemGIS, unfortunalety, I did not have so much time for now to develop further... However, we can describe you the file format and we can iterate if you want to implement this into GemGIS. I can also have a look if there is a example of exporting function in GemGIS.
Have a nice day!
Moise

**Comment by Japhiolite** [comment]
Hi @MoiseRousseau and @AlexanderJuestel ?

What is the status on this?
Were the export formats added to GemGIS? How should we proceed with this issue?

**Comment by MoiseRousseau** [comment]
Hi Japhiolite,

I implemented this capacity directly in GemPy, as for the Moose export capability. See: 

https://github.com/cgre-aachen/gempy/pull/558

Let me know what you think,

Moise

**Comment by AlexanderJuestel** [comment]
@Japhiolite I have not followed further up on this, sorry

**Comment by Japhiolite** [comment]
No worries @AlexanderJuestel 

Thanks @MoiseRousseau, I will have a look at the PR.
