### ISSUE TITLE
p3d plotting is not working.

### ISSUE THREAD

**Issue by thelearningcurves** [cgre-aachen/gempy#785]
**Describe the bug**
I was trying to follow transform 2020 tutorial. The p3d function for 3d plot is not working. When I run the cell, the notebook kernel dies and restarts again without any error. So, I tried running it in the Ubuntu terminal and got a handful of errors.
**To Reproduce**
Provide detailed steps to reproduce the behavior:

1. create a environment with python 3.10
2.install all the dependenceis including theano, GDAL, pyvista
3.run juypter notebook
4. copy codes from transfrom-2020 workshop repo from gempy 
...

**Expected behavior**
I was expecting for a 3d plot.

**Screenshots**
![GEMPY_3D_PLOTTING](https://user-images.githubusercontent.com/71737718/230713779-4aca9746-6275-4a59-9d43-5650dda816d6.png)

**Desktop (please complete the following information):**
  * Ubuntu 22 (wsl2)
  * GemPy Version 2.2.12 via pip3
    * if installed via pip: provide GemPy version (e.g. 2.0.1)
    * if cloned from GitHub: provide Git commit id (e.g. 839bf85f)
  * Jupyter Version (if applicable)

**Additional context**

**Comment by javoha** [comment]
Hi, 
thanks for sharing your problem. It might be an issue that the tutorial is quite old - but it is running for me. Can you check what happens if you just run
```Python
gp.plot_3d(geo_model)
```
after computing the model (meaning after ```gp.compute_model(geo_model)```)? Do other models like the simple geometric examples ([like this](https://docs.gempy.org/examples/geometries/1_horizontal_stratigraphic.html#sphx-glr-examples-geometries-1-horizontal-stratigraphic-py)) work for you?

**Comment by javoha** [comment]
Regarding an atlernative way, you can export the surfaces using:

```Python
gp._plot.export_to_vtk(geo_model, voxels=False)
```

**Comment by AlexanderJuestel** [comment]
@thelearningcurves did the suggestions by @javoha solve your issue?
