### ISSUE TITLE
How to build Finite fault

### ISSUE THREAD

**Issue by hembramsasmita** [cgre-aachen/gempy#787]
Hello,

I have gone through the examples of gempy models and want to know how to build finite faults in a lithology section. A simple fault model extends the fault in the whole dimension. What are the parameters needed to consider while modifying the code of fault model for finite fault?

Thank you in advance.

**Comment by NilsChudalla** [comment]
Hello @hembramsasmita, 

To make it brief: Finite faults are currently not implemented. 

Some workaround: consider the faults in gempy as a plane of offset, rather than the geological structure. If data is sufficient on hanging and foot wall, you can define the geometry of your stratigraphic (or whatever your are modeling) interfaces, so that you come up with the geometry of a finite fault. The mesh of the fault is still misleading, however, the other meshes should have the shape you require.

**Comment by hembramsasmita** [comment]
@NilsChudalla Thank you for your response. I was trying to create  synthetic geological model and wanted to know if finite fault could be possible. Anyway, thanks again.
