### ISSUE TITLE
Rename 'basement'

### ISSUE THREAD

**Issue by funveen** [cgre-aachen/gempy#83]
Depending on the convention 'well-tops' or 'well-bottoms', one might want to rename the formations. This can be done by renaming the data before importing it and using negative depth values, but could still require a change of the name 'basement'.

In many of gempy's methods, the name 'basement' is checked in order to identify the very last layer of the model. Renaming it, requires other mechanisms to check. Since the Pandas Categorical Data is used, we can take advantage of the 'ordered = True' attribute. Applying this to the category, allows to query the very last formation name ('basement'):

```
# set formation categories as ordered and check
geo_data.interfaces['formation'] = geo_data.interfaces['formation'].cat.as_ordered()
geo_data.interfaces['formation'].cat.ordered
--> True
geo_data.interfaces['formation'].max()
--> 'basement'
```

Renaming can then be done by:
```
geo_data.interfaces['formation'] = geo_data.interfaces['formation'].cat.rename_categories({'basement':'Captain'})
geo_data.interfaces['formation'].max()
--> 'Captain'
```

See https://pandas.pydata.org/pandas-docs/stable/categorical.html#sorting-and-order for reference

**Comment by ejhgeo** [comment]
I have done this to rename my basement to Mantle, but when I run `gp.get_sequential_pile(geo_data)` it still shows 'basement' not 'Mantle', so it doesn't seem to take. Also, how do I get GemPy to set the automatic basement as it's own Series? It keeps just tacking it on to my last Series, which doesn't entirely work with my data because it crosses a plate boundary - the "layers" are not simply sequentially ordered.
