### ISSUE TITLE
noisy surface from potential field method 

### ISSUE THREAD

**Issue by FranckyFouedjio** [cgre-aachen/gempy#89]
Hi,
I performed the potential field method with GemPy and another package called "RGeostats" . In a synthetic simple case, I obtained the same results (with same variogram parameters) as showed below:
![example_1_gempy](https://user-images.githubusercontent.com/40506403/44768387-fd789080-ab15-11e8-991f-8e1729084c71.png)
![example_1_rgeostats](https://user-images.githubusercontent.com/40506403/44768388-fe112700-ab15-11e8-8780-12ee267082c3.png)

However, on a another case with 200 contact points and 2 orientations data, the potential field method with GemPy  produced a noisy surface contrarily  to the RGeostats (with same variogram parameters as showed below:
![example_2_gempy](https://user-images.githubusercontent.com/40506403/44768389-fe112700-ab15-11e8-942a-b5eb3037c0bf.png)
![example_2_rgeostats](https://user-images.githubusercontent.com/40506403/44768390-fe112700-ab15-11e8-9e6a-5432b2f6cd6c.png)

Is that any explanation for that? I also noticed that sometimes the potential field method with GemPy does not pass through all the contact points even if there is no nugget effect. Is that any reason for that as the kriging is supposed to be an exact interpolator?
Thanks

**Comment by Leguark** [comment]
Hi Francky, 
I would need to see the implementation of Rgeostats to be sure we are comparing apples with apples.

The noise in gempy comes usually because a low conditional number and why has a lower conditional number the Rgeostats can be for couple of reasons: Is it the R implementation a global interpolator? Does it interpolate the the difference of scalar values or the it is assigning the scalar value to 0 at the interface?

Regarding the nugget effect, how are you changing the nugget effect? Are you using the theano setters? Today testing it, I realize that I go back to default values with a couple of methods so check that after the computation of the model the nugget effect is still 0. In the following weeks I will test this more in detail.
Cheers

**Comment by FranckyFouedjio** [comment]
Hi Miguel,

Thank you so much for your quick reply. RGeostats implementation is a
global interpolator and interpolates the difference of scalar values.

Regarding the nugget effect, I change the value using
"nugget_effect_scalar=0" in InterpolatorData and I check the value using
get_kriging_parameters.

Looking forward to hearing from you,

Cheers,

Francky
